### ISSUE TITLE
Logo / App icon

### ISSUE THREAD

**Issue by tadly** [linuxwhatelse/dups#4]
Currently I use the `security-high` status icon as logo just so I have something ':D

I'm not great with graphics design so help is very much wanted if anyone feels generous enough.

I do like the style of [Paper Icon Theme](https://snwh.org/paper) so that's something we could base a design upon?

**Comment by andeladenaro** [comment]
Hi.. My name is Andela Denaro, and I want to propose logo for your project.
Here's my design.

![dups](https://user-images.githubusercontent.com/35057858/45871873-b437fb80-bdb8-11e8-9d19-85e7723c5298.png)

I would appreciate hearing your opinion on this. Kind regards.

**Comment by andeladenaro** [comment]
I think you've caught my perspective. It's from top front view. Is that a matter? I think it still a flat design with some enhancement. So what do you think?

**Comment by tadly** [comment]
It's not bad but personally I'd prefer a flat design as it makes it look less... mmmh. busy?
Not sure how to explain it.

Looking at the paper icon theme again (f.e. the [disk-utility](https://raw.githubusercontent.com/snwh/paper-icon-theme/master/Paper/512x512/apps/disk-utility.png) icon) it just has so much simplicity to it which I really like.

I do really like the lettering and the idea with the circle inside the D (would look great in the README on github).
I think it would/could look better if the circles stroke width would match the letters stroke width?
Not sure though.

As for the icon itself... I don't know how to be of any use, sorry :/
When it comes to graphical design I can only look at things and say _"yes that's exactly it"_ or _"something's not right"_.

**Comment by andeladenaro** [comment]
Maybe you will be interested on one of this. I've edited the circles stoke arrow too.

![dups 2](https://user-images.githubusercontent.com/35057858/45880016-c58d0200-bdd0-11e8-9bfd-ea8b04b4ce31.png)

**Comment by tadly** [comment]
Certainly a big improvement!
The bigger circle stroke makes quite the difference which I like :)

The drive-enclosure as icon is a good idea and looks much better than the previous version but it still doesn't give me the _yeah that's it_ feel.
I also just now realized (while googleing for inspiration) that this concept has a lot of similarity with Apples [Time Machine](https://miapple.me/wp-content/uploads/2017/09/macOS-Time-Machine-icon-300x300.jpg) icon which I'd like to avoid.

After some debate with a friend of mine we came up with the following idea:
 - A simple rectangle (like the [disk-utility](https://raw.githubusercontent.com/snwh/paper-icon-theme/master/Paper/512x512/apps/disk-utility.png) icon) **without** the circle at the bottom right.
 - The inset would be replaced with the arrow (also inset)
 - A status indicator dot (like used before) in the bottom right corner to suggest it is a disk (I hope that works out)

Not sure if this would end up looking horrendous, dumb or just wouldn't make sense visually. 😅

Again, thanks for spending so much time and putting up with my crap 🙄
I hope it's bearable.

**Comment by andeladenaro** [comment]
No problem, i just finished the revision. I thought it become more simple icon than before. Here's I have some sample with differentiation. 

![dups 3](https://user-images.githubusercontent.com/35057858/45913045-c156f800-be55-11e8-9998-016a794e34b4.png)

**Comment by tadly** [comment]
Oh wow. Now we're really getting somewhere!

2 and 6 I **really** like.
If you don't minde, some changes I'd like to see on those two:
 - The carve-out on the upper edge I'm not to keen on.
   The idea is good but at first I though I had dirt on my screen 😅
 - The dot in white with inset (would make it pop a little more I think/hope)

That's it actually. After that we're golden I think :)

**Comment by andeladenaro** [comment]
Hi, i don't understand what kind of carve-out that you mean, but i do notice one dot here.
![image](https://user-images.githubusercontent.com/35057858/45941233-636a1200-c007-11e8-9f08-9b4ab704add9.png)

And make some changes.
Here's the result.

![dups 4](https://user-images.githubusercontent.com/35057858/45941252-77157880-c007-11e8-8b56-1e5dda624226.png)

I hope that suit your desire.

**Comment by tadly** [comment]
Yeah, that dot is exactly what I meant :)

Been playing with the latest version in gimp a little just so I don't have to try and guess whether or not a change might look good or not.

The final things I'd change are:
 - Swap logo and font location [*](#*)
 - Use white background for the light version [*](#*)
 - Use the the background color of **2** as font-color for **6** [*](#*)
 - Always make the circle the light teal color (so **2** would need to be change) [*](#*)

## *
Considering how we have basically reached the end of the design phase I'm curious about what kind of assets I'll get from you.
I'd obviously prefer something like svgs and other open formats where additional changes in color and positioning could easily be done by me.

**Comment by andeladenaro** [comment]
Here's the final result.

![dups 5](https://user-images.githubusercontent.com/35057858/45952191-675e5a00-c030-11e8-9efe-832bfa8666ac.png)

I can get you any tipe of file, svg would be great for other app design.

**Comment by tadly** [comment]
The drop-shadow with the dark font doesn't look quite right.
Shouldn't that be a dark color?

Lets go with svg than. From that I can generate whatever else I might need :)

Also, any specific website you want me to link to when adding you to the credits?

**Comment by andeladenaro** [comment]
I can set the shadow so it look darker. 

![dups banner](https://user-images.githubusercontent.com/35057858/45953342-f6b93c80-c033-11e8-9c9b-501a244ebf03.png)

I think you can add me as the contributor, no need a specific website. I just need to add the logo in the read me through pull request to become my resume. 

Here you can access [Google Drive](https://drive.google.com/open?id=1t4DOJx2HdpEiYraKNf5whtyM_i4q-ch4)'s sharing files.

**Comment by tadly** [comment]
Hm, the green shade on the drop-shadow is throwing me off.
Been playing with the svg real quick and RGBA `292929ff` seems to be working alright?

Also, as mentioned before, for the README I'd like the location of the icon and the writing to be swapped.
Reason being that the arrows aren't as close together :)

If you are going to add it to the README, make sure to add it to both the [template](https://github.com/linuxwhatelse/dups/blob/7bd73ab08860ca53b2887104a30d254c75622951/README-template.md) and the [real](https://github.com/linuxwhatelse/dups/blob/7bd73ab08860ca53b2887104a30d254c75622951/README.md) one.
If you're on unix, you can generate the real one by running the script [data/scripts/generate-readme](https://github.com/linuxwhatelse/dups/blob/7bd73ab08860ca53b2887104a30d254c75622951/data/scripts/generate-readme)

**Comment by andeladenaro** [comment]
I've change the drop-shadow. Yes it looks better.

![dups_readme](https://user-images.githubusercontent.com/35057858/45991285-60762c80-c0ae-11e8-8db7-2dc024dca7fd.png)

I'll add image to the left margin, because it seems your layout margin all to the left.

**Comment by tadly** [comment]
All done with #6
